// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cachet/v2/cachet.proto

// Package cachet.v2 is Cachet's wire contract for arbitrary tables.
//
// v1 encoded one table's schema into the protocol itself — a Record was id, tenant_id, status,
// payload and version, which is the fixture Cachet shipped with and nobody else's table. v2 carries
// a row as an ordered list of values against a descriptor the server publishes at handshake.
//
// The CONSISTENCY LEVELS ARE UNCHANGED, and that is the point of the version number. v1 and v2 mean
// exactly the same thing by STRONG, SESSION, BOUNDED and EVENTUAL; what changed is how a row is
// described. A change to the meaning of a level would be a change to CONSISTENCY.md and to the
// major version of the product, not to this file alone.
//
// An engine serves v1 and v2 simultaneously for one release. v1 is removed at 1.0.

package cachetv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsistencyLevel selects a per-request guarantee. Defined normatively in CONSISTENCY.md §3.
//
// Identical to cachet.v1.ConsistencyLevel, including the numbering, because they are the same
// guarantees. Renumbering them would imply a change nobody made.
type ConsistencyLevel int32

const (
	ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED ConsistencyLevel = 0
	ConsistencyLevel_CONSISTENCY_LEVEL_STRONG      ConsistencyLevel = 1
	ConsistencyLevel_CONSISTENCY_LEVEL_SESSION     ConsistencyLevel = 2
	ConsistencyLevel_CONSISTENCY_LEVEL_BOUNDED     ConsistencyLevel = 3
	ConsistencyLevel_CONSISTENCY_LEVEL_EVENTUAL    ConsistencyLevel = 4
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "CONSISTENCY_LEVEL_UNSPECIFIED",
		1: "CONSISTENCY_LEVEL_STRONG",
		2: "CONSISTENCY_LEVEL_SESSION",
		3: "CONSISTENCY_LEVEL_BOUNDED",
		4: "CONSISTENCY_LEVEL_EVENTUAL",
	}
	ConsistencyLevel_value = map[string]int32{
		"CONSISTENCY_LEVEL_UNSPECIFIED": 0,
		"CONSISTENCY_LEVEL_STRONG":      1,
		"CONSISTENCY_LEVEL_SESSION":     2,
		"CONSISTENCY_LEVEL_BOUNDED":     3,
		"CONSISTENCY_LEVEL_EVENTUAL":    4,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_cachet_v2_cachet_proto_enumTypes[0].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_cachet_v2_cachet_proto_enumTypes[0]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{0}
}

// Value is one column of one row.
//
// is_null is carried explicitly rather than being inferred from empty data, because SQL NULL and a
// zero-length value are different facts — and both are different again from the row not existing,
// which GetResponse.found reports. Three absences, all distinct, none collapsible.
type Value struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	IsNull bool                   `protobuf:"varint,1,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	// The bytes MySQL produced, unparsed. Integers are decimal text, DECIMAL and DATETIME are the
	// text they were stored as. A client that wants a typed value parses it against the column type
	// the descriptor gives it — which is strictly more information than a pre-parsed field would
	// carry, and loses nothing on the way.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

func (x *Value) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Row is one row, in the descriptor's column order.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// ColumnDescriptor describes one cached column.
type ColumnDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnDescriptor) Reset() {
	*x = ColumnDescriptor{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDescriptor) ProtoMessage() {}

func (x *ColumnDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDescriptor.ProtoReflect.Descriptor instead.
func (*ColumnDescriptor) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnDescriptor) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

// TableDescriptor tells a client how to read a Row.
//
// Published at handshake so a client never has to be configured with a copy of the server's schema.
// Two copies of a schema is two things to drift.
type TableDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnDescriptor    `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	PrimaryKey    []string               `protobuf:"bytes,3,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	VersionColumn string                 `protobuf:"bytes,4,opt,name=version_column,json=versionColumn,proto3" json:"version_column,omitempty"`
	// Fingerprint identifies the row SHAPE. A client that cached anything keyed on it can tell that
	// the server's schema changed without comparing column lists.
	Fingerprint   string `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableDescriptor) Reset() {
	*x = TableDescriptor{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableDescriptor) ProtoMessage() {}

func (x *TableDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableDescriptor.ProtoReflect.Descriptor instead.
func (*TableDescriptor) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{3}
}

func (x *TableDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableDescriptor) GetColumns() []*ColumnDescriptor {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableDescriptor) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *TableDescriptor) GetVersionColumn() string {
	if x != nil {
		return x.VersionColumn
	}
	return ""
}

func (x *TableDescriptor) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type SessionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watermarks    map[string]uint64      `protobuf:"bytes,1,rep,name=watermarks,proto3" json:"watermarks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken) Reset() {
	*x = SessionToken{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken) ProtoMessage() {}

func (x *SessionToken) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken.ProtoReflect.Descriptor instead.
func (*SessionToken) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{4}
}

func (x *SessionToken) GetWatermarks() map[string]uint64 {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

type ReadMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LevelServed    ConsistencyLevel       `protobuf:"varint,1,opt,name=level_served,json=levelServed,proto3,enum=cachet.v2.ConsistencyLevel" json:"level_served,omitempty"`
	Degraded       bool                   `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason string                 `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	CacheHit       bool                   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	RowVersion     uint64                 `protobuf:"varint,5,opt,name=row_version,json=rowVersion,proto3" json:"row_version,omitempty"`
	FillVersion    uint64                 `protobuf:"varint,6,opt,name=fill_version,json=fillVersion,proto3" json:"fill_version,omitempty"`
	// How stale this answer may be, when something about serving it weakened the promise.
	//
	// Set when degraded is true and the weakening has a duration — a read served from the gutter
	// pool while its home cache node is not answering is bounded by the gutter TTL, because nothing
	// invalidates a gutter entry. A degraded read without a number is a degraded read the caller
	// cannot act on.
	EffectiveStalenessBound *durationpb.Duration `protobuf:"bytes,7,opt,name=effective_staleness_bound,json=effectiveStalenessBound,proto3" json:"effective_staleness_bound,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReadMeta) Reset() {
	*x = ReadMeta{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMeta) ProtoMessage() {}

func (x *ReadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMeta.ProtoReflect.Descriptor instead.
func (*ReadMeta) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMeta) GetLevelServed() ConsistencyLevel {
	if x != nil {
		return x.LevelServed
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *ReadMeta) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ReadMeta) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *ReadMeta) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *ReadMeta) GetRowVersion() uint64 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

func (x *ReadMeta) GetFillVersion() uint64 {
	if x != nil {
		return x.FillVersion
	}
	return 0
}

func (x *ReadMeta) GetEffectiveStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.EffectiveStalenessBound
	}
	return nil
}

type WriteMeta struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Version                 uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Degraded                bool                   `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason          string                 `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	EffectiveStalenessBound *durationpb.Duration   `protobuf:"bytes,4,opt,name=effective_staleness_bound,json=effectiveStalenessBound,proto3" json:"effective_staleness_bound,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WriteMeta) Reset() {
	*x = WriteMeta{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMeta) ProtoMessage() {}

func (x *WriteMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMeta.ProtoReflect.Descriptor instead.
func (*WriteMeta) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{6}
}

func (x *WriteMeta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WriteMeta) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *WriteMeta) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *WriteMeta) GetEffectiveStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.EffectiveStalenessBound
	}
	return nil
}

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion   string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{7}
}

func (x *HandshakeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion   string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Compatible      bool                   `protobuf:"varint,3,opt,name=compatible,proto3" json:"compatible,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Every table this engine serves. A client reads rows against these.
	Tables        []*TableDescriptor `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *HandshakeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeResponse) GetTables() []*TableDescriptor {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is "<table>:<value>[:<value>…]", percent-escaped. The same grammar the CDC tailer and the
	// operator CLI use, so one string names a row everywhere in the system.
	Key            string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Level          ConsistencyLevel     `protobuf:"varint,2,opt,name=level,proto3,enum=cachet.v2.ConsistencyLevel" json:"level,omitempty"`
	StalenessBound *durationpb.Duration `protobuf:"bytes,3,opt,name=staleness_bound,json=stalenessBound,proto3" json:"staleness_bound,omitempty"`
	Session        *SessionToken        `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{9}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *GetRequest) GetStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.StalenessBound
	}
	return nil
}

func (x *GetRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absence is a first-class answer rather than an error: "this row does not exist" is a cacheable
	// fact, and an insert must later invalidate that negative entry.
	Found         bool          `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Row           *Row          `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	Meta          *ReadMeta     `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{10}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetRow() *Row {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *GetResponse) GetMeta() *ReadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type BatchGetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keys           []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Level          ConsistencyLevel       `protobuf:"varint,2,opt,name=level,proto3,enum=cachet.v2.ConsistencyLevel" json:"level,omitempty"`
	StalenessBound *durationpb.Duration   `protobuf:"bytes,3,opt,name=staleness_bound,json=stalenessBound,proto3" json:"staleness_bound,omitempty"`
	Session        *SessionToken          `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *BatchGetRequest) GetStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.StalenessBound
	}
	return nil
}

func (x *BatchGetRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type BatchGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed by the request's key strings. Absent keys are omitted rather than returned empty, so a
	// caller tells "missing" from "present but empty" by map membership.
	Rows          map[string]*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta          *ReadMeta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetResponse) GetRows() map[string]*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *BatchGetResponse) GetMeta() *ReadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BatchGetResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Row           *Row                   `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{13}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetRow() *Row {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *PutRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *WriteMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{14}
}

func (x *PutResponse) GetMeta() *WriteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PutResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	Meta          *WriteMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

func (x *DeleteResponse) GetMeta() *WriteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

// Comparison is one equality test in a conditional write's predicate.
//
// Equality only, and against a column the server has declared. Anything richer re-creates the
// problem the architecture exists to escape: a proxy that must understand arbitrary SQL to know
// what a statement touched.
type Comparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparison) Reset() {
	*x = Comparison{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparison) ProtoMessage() {}

func (x *Comparison) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparison.ProtoReflect.Descriptor instead.
func (*Comparison) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{17}
}

func (x *Comparison) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Comparison) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{18}
}

func (x *Assignment) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Assignment) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpdateWhereRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Match         []*Comparison          `protobuf:"bytes,2,rep,name=match,proto3" json:"match,omitempty"`
	Set           []*Assignment          `protobuf:"bytes,3,rep,name=set,proto3" json:"set,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWhereRequest) Reset() {
	*x = UpdateWhereRequest{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWhereRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWhereRequest) ProtoMessage() {}

func (x *UpdateWhereRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWhereRequest.ProtoReflect.Descriptor instead.
func (*UpdateWhereRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateWhereRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateWhereRequest) GetMatch() []*Comparison {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *UpdateWhereRequest) GetSet() []*Assignment {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *UpdateWhereRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type UpdateWhereResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *WriteMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// matched is the blast radius, reported whether or not the keys were resolved exactly.
	Matched uint64 `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	// affected_keys is exact when meta.degraded is false and EMPTY when it is true — never partial.
	// A partial list would leave a caller unable to tell which rows still need treating as stale.
	AffectedKeys  []string      `protobuf:"bytes,3,rep,name=affected_keys,json=affectedKeys,proto3" json:"affected_keys,omitempty"`
	Session       *SessionToken `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWhereResponse) Reset() {
	*x = UpdateWhereResponse{}
	mi := &file_cachet_v2_cachet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWhereResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWhereResponse) ProtoMessage() {}

func (x *UpdateWhereResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v2_cachet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWhereResponse.ProtoReflect.Descriptor instead.
func (*UpdateWhereResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v2_cachet_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateWhereResponse) GetMeta() *WriteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UpdateWhereResponse) GetMatched() uint64 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *UpdateWhereResponse) GetAffectedKeys() []string {
	if x != nil {
		return x.AffectedKeys
	}
	return nil
}

func (x *UpdateWhereResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_cachet_v2_cachet_proto protoreflect.FileDescriptor

const file_cachet_v2_cachet_proto_rawDesc = "" +
	"\n" +
	"\x16cachet/v2/cachet.proto\x12\tcachet.v2\x1a\x1egoogle/protobuf/duration.proto\"4\n" +
	"\x05Value\x12\x17\n" +
	"\ais_null\x18\x01 \x01(\bR\x06isNull\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x03Row\x12(\n" +
	"\x06values\x18\x01 \x03(\v2\x10.cachet.v2.ValueR\x06values\"V\n" +
	"\x10ColumnDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\"\xc6\x01\n" +
	"\x0fTableDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\acolumns\x18\x02 \x03(\v2\x1b.cachet.v2.ColumnDescriptorR\acolumns\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x03(\tR\n" +
	"primaryKey\x12%\n" +
	"\x0eversion_column\x18\x04 \x01(\tR\rversionColumn\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\"\x96\x01\n" +
	"\fSessionToken\x12G\n" +
	"\n" +
	"watermarks\x18\x01 \x03(\v2'.cachet.v2.SessionToken.WatermarksEntryR\n" +
	"watermarks\x1a=\n" +
	"\x0fWatermarksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xc7\x02\n" +
	"\bReadMeta\x12>\n" +
	"\flevel_served\x18\x01 \x01(\x0e2\x1b.cachet.v2.ConsistencyLevelR\vlevelServed\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12\x1f\n" +
	"\vrow_version\x18\x05 \x01(\x04R\n" +
	"rowVersion\x12!\n" +
	"\ffill_version\x18\x06 \x01(\x04R\vfillVersion\x12U\n" +
	"\x19effective_staleness_bound\x18\a \x01(\v2\x19.google.protobuf.DurationR\x17effectiveStalenessBound\"\xc1\x01\n" +
	"\tWriteMeta\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12U\n" +
	"\x19effective_staleness_bound\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x17effectiveStalenessBound\"d\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\"\xd1\x01\n" +
	"\x11HandshakeResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1e\n" +
	"\n" +
	"compatible\x18\x03 \x01(\bR\n" +
	"compatible\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x122\n" +
	"\x06tables\x18\x05 \x03(\v2\x1a.cachet.v2.TableDescriptorR\x06tables\"\xc8\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1b.cachet.v2.ConsistencyLevelR\x05level\x12B\n" +
	"\x0fstaleness_bound\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0estalenessBound\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"\xa1\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12 \n" +
	"\x03row\x18\x02 \x01(\v2\x0e.cachet.v2.RowR\x03row\x12'\n" +
	"\x04meta\x18\x03 \x01(\v2\x13.cachet.v2.ReadMetaR\x04meta\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"\xcf\x01\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x121\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1b.cachet.v2.ConsistencyLevelR\x05level\x12B\n" +
	"\x0fstaleness_bound\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0estalenessBound\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"\xf2\x01\n" +
	"\x10BatchGetResponse\x129\n" +
	"\x04rows\x18\x01 \x03(\v2%.cachet.v2.BatchGetResponse.RowsEntryR\x04rows\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.cachet.v2.ReadMetaR\x04meta\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\x1aG\n" +
	"\tRowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.cachet.v2.RowR\x05value:\x028\x01\"s\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x03row\x18\x02 \x01(\v2\x0e.cachet.v2.RowR\x03row\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"j\n" +
	"\vPutResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.cachet.v2.WriteMetaR\x04meta\x121\n" +
	"\asession\x18\x02 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"T\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\asession\x18\x02 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"\x87\x01\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.cachet.v2.WriteMetaR\x04meta\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"L\n" +
	"\n" +
	"Comparison\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.cachet.v2.ValueR\x05value\"L\n" +
	"\n" +
	"Assignment\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.cachet.v2.ValueR\x05value\"\xb3\x01\n" +
	"\x12UpdateWhereRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12+\n" +
	"\x05match\x18\x02 \x03(\v2\x15.cachet.v2.ComparisonR\x05match\x12'\n" +
	"\x03set\x18\x03 \x03(\v2\x15.cachet.v2.AssignmentR\x03set\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v2.SessionTokenR\asession\"\xb1\x01\n" +
	"\x13UpdateWhereResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.cachet.v2.WriteMetaR\x04meta\x12\x18\n" +
	"\amatched\x18\x02 \x01(\x04R\amatched\x12#\n" +
	"\raffected_keys\x18\x03 \x03(\tR\faffectedKeys\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v2.SessionTokenR\asession*\xb1\x01\n" +
	"\x10ConsistencyLevel\x12!\n" +
	"\x1dCONSISTENCY_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSISTENCY_LEVEL_STRONG\x10\x01\x12\x1d\n" +
	"\x19CONSISTENCY_LEVEL_SESSION\x10\x02\x12\x1d\n" +
	"\x19CONSISTENCY_LEVEL_BOUNDED\x10\x03\x12\x1e\n" +
	"\x1aCONSISTENCY_LEVEL_EVENTUAL\x10\x042\x94\x03\n" +
	"\fCacheService\x12F\n" +
	"\tHandshake\x12\x1b.cachet.v2.HandshakeRequest\x1a\x1c.cachet.v2.HandshakeResponse\x124\n" +
	"\x03Get\x12\x15.cachet.v2.GetRequest\x1a\x16.cachet.v2.GetResponse\x12C\n" +
	"\bBatchGet\x12\x1a.cachet.v2.BatchGetRequest\x1a\x1b.cachet.v2.BatchGetResponse\x124\n" +
	"\x03Put\x12\x15.cachet.v2.PutRequest\x1a\x16.cachet.v2.PutResponse\x12=\n" +
	"\x06Delete\x12\x18.cachet.v2.DeleteRequest\x1a\x19.cachet.v2.DeleteResponse\x12L\n" +
	"\vUpdateWhere\x12\x1d.cachet.v2.UpdateWhereRequest\x1a\x1e.cachet.v2.UpdateWhereResponseB;Z9github.com/Abhishek-Mallick/cachet/api/cachet/v2;cachetv2b\x06proto3"

var (
	file_cachet_v2_cachet_proto_rawDescOnce sync.Once
	file_cachet_v2_cachet_proto_rawDescData []byte
)

func file_cachet_v2_cachet_proto_rawDescGZIP() []byte {
	file_cachet_v2_cachet_proto_rawDescOnce.Do(func() {
		file_cachet_v2_cachet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cachet_v2_cachet_proto_rawDesc), len(file_cachet_v2_cachet_proto_rawDesc)))
	})
	return file_cachet_v2_cachet_proto_rawDescData
}

var file_cachet_v2_cachet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cachet_v2_cachet_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cachet_v2_cachet_proto_goTypes = []any{
	(ConsistencyLevel)(0),       // 0: cachet.v2.ConsistencyLevel
	(*Value)(nil),               // 1: cachet.v2.Value
	(*Row)(nil),                 // 2: cachet.v2.Row
	(*ColumnDescriptor)(nil),    // 3: cachet.v2.ColumnDescriptor
	(*TableDescriptor)(nil),     // 4: cachet.v2.TableDescriptor
	(*SessionToken)(nil),        // 5: cachet.v2.SessionToken
	(*ReadMeta)(nil),            // 6: cachet.v2.ReadMeta
	(*WriteMeta)(nil),           // 7: cachet.v2.WriteMeta
	(*HandshakeRequest)(nil),    // 8: cachet.v2.HandshakeRequest
	(*HandshakeResponse)(nil),   // 9: cachet.v2.HandshakeResponse
	(*GetRequest)(nil),          // 10: cachet.v2.GetRequest
	(*GetResponse)(nil),         // 11: cachet.v2.GetResponse
	(*BatchGetRequest)(nil),     // 12: cachet.v2.BatchGetRequest
	(*BatchGetResponse)(nil),    // 13: cachet.v2.BatchGetResponse
	(*PutRequest)(nil),          // 14: cachet.v2.PutRequest
	(*PutResponse)(nil),         // 15: cachet.v2.PutResponse
	(*DeleteRequest)(nil),       // 16: cachet.v2.DeleteRequest
	(*DeleteResponse)(nil),      // 17: cachet.v2.DeleteResponse
	(*Comparison)(nil),          // 18: cachet.v2.Comparison
	(*Assignment)(nil),          // 19: cachet.v2.Assignment
	(*UpdateWhereRequest)(nil),  // 20: cachet.v2.UpdateWhereRequest
	(*UpdateWhereResponse)(nil), // 21: cachet.v2.UpdateWhereResponse
	nil,                         // 22: cachet.v2.SessionToken.WatermarksEntry
	nil,                         // 23: cachet.v2.BatchGetResponse.RowsEntry
	(*durationpb.Duration)(nil), // 24: google.protobuf.Duration
}
var file_cachet_v2_cachet_proto_depIdxs = []int32{
	1,  // 0: cachet.v2.Row.values:type_name -> cachet.v2.Value
	3,  // 1: cachet.v2.TableDescriptor.columns:type_name -> cachet.v2.ColumnDescriptor
	22, // 2: cachet.v2.SessionToken.watermarks:type_name -> cachet.v2.SessionToken.WatermarksEntry
	0,  // 3: cachet.v2.ReadMeta.level_served:type_name -> cachet.v2.ConsistencyLevel
	24, // 4: cachet.v2.ReadMeta.effective_staleness_bound:type_name -> google.protobuf.Duration
	24, // 5: cachet.v2.WriteMeta.effective_staleness_bound:type_name -> google.protobuf.Duration
	4,  // 6: cachet.v2.HandshakeResponse.tables:type_name -> cachet.v2.TableDescriptor
	0,  // 7: cachet.v2.GetRequest.level:type_name -> cachet.v2.ConsistencyLevel
	24, // 8: cachet.v2.GetRequest.staleness_bound:type_name -> google.protobuf.Duration
	5,  // 9: cachet.v2.GetRequest.session:type_name -> cachet.v2.SessionToken
	2,  // 10: cachet.v2.GetResponse.row:type_name -> cachet.v2.Row
	6,  // 11: cachet.v2.GetResponse.meta:type_name -> cachet.v2.ReadMeta
	5,  // 12: cachet.v2.GetResponse.session:type_name -> cachet.v2.SessionToken
	0,  // 13: cachet.v2.BatchGetRequest.level:type_name -> cachet.v2.ConsistencyLevel
	24, // 14: cachet.v2.BatchGetRequest.staleness_bound:type_name -> google.protobuf.Duration
	5,  // 15: cachet.v2.BatchGetRequest.session:type_name -> cachet.v2.SessionToken
	23, // 16: cachet.v2.BatchGetResponse.rows:type_name -> cachet.v2.BatchGetResponse.RowsEntry
	6,  // 17: cachet.v2.BatchGetResponse.meta:type_name -> cachet.v2.ReadMeta
	5,  // 18: cachet.v2.BatchGetResponse.session:type_name -> cachet.v2.SessionToken
	2,  // 19: cachet.v2.PutRequest.row:type_name -> cachet.v2.Row
	5,  // 20: cachet.v2.PutRequest.session:type_name -> cachet.v2.SessionToken
	7,  // 21: cachet.v2.PutResponse.meta:type_name -> cachet.v2.WriteMeta
	5,  // 22: cachet.v2.PutResponse.session:type_name -> cachet.v2.SessionToken
	5,  // 23: cachet.v2.DeleteRequest.session:type_name -> cachet.v2.SessionToken
	7,  // 24: cachet.v2.DeleteResponse.meta:type_name -> cachet.v2.WriteMeta
	5,  // 25: cachet.v2.DeleteResponse.session:type_name -> cachet.v2.SessionToken
	1,  // 26: cachet.v2.Comparison.value:type_name -> cachet.v2.Value
	1,  // 27: cachet.v2.Assignment.value:type_name -> cachet.v2.Value
	18, // 28: cachet.v2.UpdateWhereRequest.match:type_name -> cachet.v2.Comparison
	19, // 29: cachet.v2.UpdateWhereRequest.set:type_name -> cachet.v2.Assignment
	5,  // 30: cachet.v2.UpdateWhereRequest.session:type_name -> cachet.v2.SessionToken
	7,  // 31: cachet.v2.UpdateWhereResponse.meta:type_name -> cachet.v2.WriteMeta
	5,  // 32: cachet.v2.UpdateWhereResponse.session:type_name -> cachet.v2.SessionToken
	2,  // 33: cachet.v2.BatchGetResponse.RowsEntry.value:type_name -> cachet.v2.Row
	8,  // 34: cachet.v2.CacheService.Handshake:input_type -> cachet.v2.HandshakeRequest
	10, // 35: cachet.v2.CacheService.Get:input_type -> cachet.v2.GetRequest
	12, // 36: cachet.v2.CacheService.BatchGet:input_type -> cachet.v2.BatchGetRequest
	14, // 37: cachet.v2.CacheService.Put:input_type -> cachet.v2.PutRequest
	16, // 38: cachet.v2.CacheService.Delete:input_type -> cachet.v2.DeleteRequest
	20, // 39: cachet.v2.CacheService.UpdateWhere:input_type -> cachet.v2.UpdateWhereRequest
	9,  // 40: cachet.v2.CacheService.Handshake:output_type -> cachet.v2.HandshakeResponse
	11, // 41: cachet.v2.CacheService.Get:output_type -> cachet.v2.GetResponse
	13, // 42: cachet.v2.CacheService.BatchGet:output_type -> cachet.v2.BatchGetResponse
	15, // 43: cachet.v2.CacheService.Put:output_type -> cachet.v2.PutResponse
	17, // 44: cachet.v2.CacheService.Delete:output_type -> cachet.v2.DeleteResponse
	21, // 45: cachet.v2.CacheService.UpdateWhere:output_type -> cachet.v2.UpdateWhereResponse
	40, // [40:46] is the sub-list for method output_type
	34, // [34:40] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_cachet_v2_cachet_proto_init() }
func file_cachet_v2_cachet_proto_init() {
	if File_cachet_v2_cachet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cachet_v2_cachet_proto_rawDesc), len(file_cachet_v2_cachet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cachet_v2_cachet_proto_goTypes,
		DependencyIndexes: file_cachet_v2_cachet_proto_depIdxs,
		EnumInfos:         file_cachet_v2_cachet_proto_enumTypes,
		MessageInfos:      file_cachet_v2_cachet_proto_msgTypes,
	}.Build()
	File_cachet_v2_cachet_proto = out.File
	file_cachet_v2_cachet_proto_goTypes = nil
	file_cachet_v2_cachet_proto_depIdxs = nil
}
