# Sextant — is your cache as consistent as you think it is?
#
# Generated by scripts/gen-homebrew-formula.py from the checksums of a published release. Do not
# edit by hand.
#
# Sextant verifies ANY cache, not only Cachet's: point it at a Redis and the database behind it and
# it publishes a measured consistency figure per level, with the comparison it made as a label. It
# has its own formula because that is how it is meant to be installed — by somebody who has a cache
# and a doubt, not by somebody deploying Cachet.
#
#     brew tap abhishek-mallick/cachet https://github.com/Abhishek-Mallick/cachet
#     brew install sextant
class Sextant < Formula
  desc "Verify that a cache is as consistent as it claims - measured, per consistency level"
  homepage "https://github.com/Abhishek-Mallick/cachet"
  version "9.9.9"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Abhishek-Mallick/cachet/releases/download/v9.9.9/cachet_9.9.9_darwin_arm64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/cachet/releases/download/v9.9.9/cachet_9.9.9_darwin_amd64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Abhishek-Mallick/cachet/releases/download/v9.9.9/cachet_9.9.9_linux_arm64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/cachet/releases/download/v9.9.9/cachet_9.9.9_linux_amd64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
  end


  def install
    bin.install "sextant"
  end

  test do
    assert_match "sextant", shell_output("#{bin}/sextant -version")
  end
end
