// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cachet/v1/cachet.proto

// Package cachet.v1 is Cachet's wire contract.
//
// The protocol is versioned independently of the binaries (delivery model §7): an engine and an SDK
// WILL drift in the field, so Handshake exists from day one rather than being added after the first
// support incident.
//
// A change to the meaning of any ConsistencyLevel is a MAJOR version change and lands in cachet.v2.
// The guarantee is the contract — see CONSISTENCY.md.

package cachetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsistencyLevel selects a per-request guarantee. Defined normatively in CONSISTENCY.md §3.
type ConsistencyLevel int32

const (
	// Unspecified is treated as SESSION, which is the documented default. A client that forgets to
	// choose gets read-own-writes rather than silently getting the weakest option.
	ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED ConsistencyLevel = 0
	// Bypasses the cache entirely. Money, auth, anything serializable.
	ConsistencyLevel_CONSISTENCY_LEVEL_STRONG ConsistencyLevel = 1
	// Read-own-writes plus monotonic reads, scoped to the session token. The default.
	ConsistencyLevel_CONSISTENCY_LEVEL_SESSION ConsistencyLevel = 2
	// SESSION plus a freshness floor: staleness bounded by staleness_bound, measured from COMMIT
	// time, not read time. Requires staleness_bound to be set.
	ConsistencyLevel_CONSISTENCY_LEVEL_BOUNDED ConsistencyLevel = 3
	// Best effort. No read-own-writes, no monotonic reads. Exists to make the cost of the other
	// levels visible in the benchmark table.
	ConsistencyLevel_CONSISTENCY_LEVEL_EVENTUAL ConsistencyLevel = 4
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "CONSISTENCY_LEVEL_UNSPECIFIED",
		1: "CONSISTENCY_LEVEL_STRONG",
		2: "CONSISTENCY_LEVEL_SESSION",
		3: "CONSISTENCY_LEVEL_BOUNDED",
		4: "CONSISTENCY_LEVEL_EVENTUAL",
	}
	ConsistencyLevel_value = map[string]int32{
		"CONSISTENCY_LEVEL_UNSPECIFIED": 0,
		"CONSISTENCY_LEVEL_STRONG":      1,
		"CONSISTENCY_LEVEL_SESSION":     2,
		"CONSISTENCY_LEVEL_BOUNDED":     3,
		"CONSISTENCY_LEVEL_EVENTUAL":    4,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_cachet_v1_cachet_proto_enumTypes[0].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_cachet_v1_cachet_proto_enumTypes[0]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{0}
}

// SessionToken carries a session's causal position.
//
// It is a sparse map from shard id to HLC version, NOT a scalar, because each shard runs its own
// clock and versions from different shards are incomparable (ADR 0003). It is held by the client,
// not the server: that is what lets the guarantee survive a reconnect or an engine failover, since
// engines are stateless with respect to sessions (CONSISTENCY.md §4).
type SessionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watermarks    map[string]uint64      `protobuf:"bytes,1,rep,name=watermarks,proto3" json:"watermarks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken) Reset() {
	*x = SessionToken{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken) ProtoMessage() {}

func (x *SessionToken) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken.ProtoReflect.Descriptor instead.
func (*SessionToken) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{0}
}

func (x *SessionToken) GetWatermarks() map[string]uint64 {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

// Record is one cached row.
type Record struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status   uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Payload  []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// The HLC version of the write that last modified this row. Maintained by Cachet, never by the
	// application.
	Version       uint64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Record) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Record) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ReadMeta reports what actually happened, as distinct from what was asked for.
type ReadMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The level actually served. It may be weaker than the level requested — see degraded.
	LevelServed ConsistencyLevel `protobuf:"varint,1,opt,name=level_served,json=levelServed,proto3,enum=cachet.v1.ConsistencyLevel" json:"level_served,omitempty"`
	// True when the engine could not honour the requested level and served a weaker one. Ignoring
	// this is the caller's decision, but it must be a VISIBLE decision: a silent downgrade of a
	// stated guarantee is precisely the failure Cachet exists to eliminate.
	Degraded       bool   `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason string `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	CacheHit       bool   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	// The row's own version, and the shard-state version the served entry reflects. Both are exposed
	// because they answer different questions, and conflating them is a correctness bug rather than
	// an inefficiency (CONSISTENCY.md §1).
	RowVersion    uint64 `protobuf:"varint,5,opt,name=row_version,json=rowVersion,proto3" json:"row_version,omitempty"`
	FillVersion   uint64 `protobuf:"varint,6,opt,name=fill_version,json=fillVersion,proto3" json:"fill_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMeta) Reset() {
	*x = ReadMeta{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMeta) ProtoMessage() {}

func (x *ReadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMeta.ProtoReflect.Descriptor instead.
func (*ReadMeta) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{2}
}

func (x *ReadMeta) GetLevelServed() ConsistencyLevel {
	if x != nil {
		return x.LevelServed
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *ReadMeta) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ReadMeta) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *ReadMeta) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *ReadMeta) GetRowVersion() uint64 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

func (x *ReadMeta) GetFillVersion() uint64 {
	if x != nil {
		return x.FillVersion
	}
	return 0
}

// WriteMeta reports what a write actually did.
type WriteMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the write committed at. This is what advances the caller's session watermark.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Set when exact affected-key resolution was abandoned because the predicate matched more than
	// max_affected_keys rows, leaving invalidation to CDC. The writer's OWN session guarantee still
	// holds; other sessions' reads of those keys become BOUNDED(cdc_lag_bound). CONSISTENCY.md §5.
	Degraded                bool                 `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason          string               `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	EffectiveStalenessBound *durationpb.Duration `protobuf:"bytes,4,opt,name=effective_staleness_bound,json=effectiveStalenessBound,proto3" json:"effective_staleness_bound,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WriteMeta) Reset() {
	*x = WriteMeta{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMeta) ProtoMessage() {}

func (x *WriteMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMeta.ProtoReflect.Descriptor instead.
func (*WriteMeta) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{3}
}

func (x *WriteMeta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WriteMeta) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *WriteMeta) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *WriteMeta) GetEffectiveStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.EffectiveStalenessBound
	}
	return nil
}

type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Level ConsistencyLevel       `protobuf:"varint,2,opt,name=level,proto3,enum=cachet.v1.ConsistencyLevel" json:"level,omitempty"`
	// Required when level is BOUNDED, rejected otherwise. Measured from commit time.
	StalenessBound *durationpb.Duration `protobuf:"bytes,3,opt,name=staleness_bound,json=stalenessBound,proto3" json:"staleness_bound,omitempty"`
	Session        *SessionToken        `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *GetRequest) GetStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.StalenessBound
	}
	return nil
}

func (x *GetRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absence is a first-class answer, not an error: "this row does not exist" is a cacheable fact,
	// and an insert must later invalidate that negative entry.
	Found  bool      `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Record *Record   `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Meta   *ReadMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// The caller's session token, advanced by this read. Monotonic reads come from the client
	// carrying this forward.
	Session       *SessionToken `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetResponse) GetMeta() *ReadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type BatchGetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keys           []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Level          ConsistencyLevel       `protobuf:"varint,2,opt,name=level,proto3,enum=cachet.v1.ConsistencyLevel" json:"level,omitempty"`
	StalenessBound *durationpb.Duration   `protobuf:"bytes,3,opt,name=staleness_bound,json=stalenessBound,proto3" json:"staleness_bound,omitempty"`
	Session        *SessionToken          `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED
}

func (x *BatchGetRequest) GetStalenessBound() *durationpb.Duration {
	if x != nil {
		return x.StalenessBound
	}
	return nil
}

func (x *BatchGetRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

// BatchGetResponse holds one entry per key that exists.
//
// There is deliberately no cross-key snapshot at any level: Cachet caches rows, not transactions,
// and a batch is N independent reads. CONSISTENCY.md §6.
type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       map[string]*Record     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta          *ReadMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetResponse) GetRecords() map[string]*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *BatchGetResponse) GetMeta() *ReadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BatchGetResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{8}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *PutRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *WriteMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{9}
}

func (x *PutResponse) GetMeta() *WriteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PutResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Session       *SessionToken          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when the row did not exist. Deleting an absent row is not an error, but the caller is
	// told, because it determines whether a negative cache entry needed invalidating.
	Existed       bool          `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	Meta          *WriteMeta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *SessionToken `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

func (x *DeleteResponse) GetMeta() *WriteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteResponse) GetSession() *SessionToken {
	if x != nil {
		return x.Session
	}
	return nil
}

type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol version the client was built against, e.g. "cachet.v1".
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientVersion   string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{12}
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// True when the server can serve this client. False is not an error status: it lets the SDK log
	// a precise, actionable message instead of failing on an unrelated field later.
	Compatible            bool   `protobuf:"varint,3,opt,name=compatible,proto3" json:"compatible,omitempty"`
	IncompatibilityReason string `protobuf:"bytes,4,opt,name=incompatibility_reason,json=incompatibilityReason,proto3" json:"incompatibility_reason,omitempty"`
	// Levels this server will actually serve. A client can then fail fast at startup rather than on
	// the first request that asks for something unsupported.
	SupportedLevels []ConsistencyLevel `protobuf:"varint,5,rep,packed,name=supported_levels,json=supportedLevels,proto3,enum=cachet.v1.ConsistencyLevel" json:"supported_levels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_cachet_v1_cachet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cachet_v1_cachet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_cachet_v1_cachet_proto_rawDescGZIP(), []int{13}
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *HandshakeResponse) GetIncompatibilityReason() string {
	if x != nil {
		return x.IncompatibilityReason
	}
	return ""
}

func (x *HandshakeResponse) GetSupportedLevels() []ConsistencyLevel {
	if x != nil {
		return x.SupportedLevels
	}
	return nil
}

var File_cachet_v1_cachet_proto protoreflect.FileDescriptor

const file_cachet_v1_cachet_proto_rawDesc = "" +
	"\n" +
	"\x16cachet/v1/cachet.proto\x12\tcachet.v1\x1a\x1egoogle/protobuf/duration.proto\"\x96\x01\n" +
	"\fSessionToken\x12G\n" +
	"\n" +
	"watermarks\x18\x01 \x03(\v2'.cachet.v1.SessionToken.WatermarksEntryR\n" +
	"watermarks\x1a=\n" +
	"\x0fWatermarksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x81\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"\xf0\x01\n" +
	"\bReadMeta\x12>\n" +
	"\flevel_served\x18\x01 \x01(\x0e2\x1b.cachet.v1.ConsistencyLevelR\vlevelServed\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12\x1f\n" +
	"\vrow_version\x18\x05 \x01(\x04R\n" +
	"rowVersion\x12!\n" +
	"\ffill_version\x18\x06 \x01(\x04R\vfillVersion\"\xc1\x01\n" +
	"\tWriteMeta\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12U\n" +
	"\x19effective_staleness_bound\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x17effectiveStalenessBound\"\xc8\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1b.cachet.v1.ConsistencyLevelR\x05level\x12B\n" +
	"\x0fstaleness_bound\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0estalenessBound\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"\xaa\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12)\n" +
	"\x06record\x18\x02 \x01(\v2\x11.cachet.v1.RecordR\x06record\x12'\n" +
	"\x04meta\x18\x03 \x01(\v2\x13.cachet.v1.ReadMetaR\x04meta\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"\xcf\x01\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x121\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1b.cachet.v1.ConsistencyLevelR\x05level\x12B\n" +
	"\x0fstaleness_bound\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0estalenessBound\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"\x81\x02\n" +
	"\x10BatchGetResponse\x12B\n" +
	"\arecords\x18\x01 \x03(\v2(.cachet.v1.BatchGetResponse.RecordsEntryR\arecords\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.cachet.v1.ReadMetaR\x04meta\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\x1aM\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cachet.v1.RecordR\x05value:\x028\x01\"|\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x06record\x18\x02 \x01(\v2\x11.cachet.v1.RecordR\x06record\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"j\n" +
	"\vPutResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.cachet.v1.WriteMetaR\x04meta\x121\n" +
	"\asession\x18\x02 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"T\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\asession\x18\x02 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"\x87\x01\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.cachet.v1.WriteMetaR\x04meta\x121\n" +
	"\asession\x18\x03 \x01(\v2\x17.cachet.v1.SessionTokenR\asession\"d\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"\x84\x02\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x1e\n" +
	"\n" +
	"compatible\x18\x03 \x01(\bR\n" +
	"compatible\x125\n" +
	"\x16incompatibility_reason\x18\x04 \x01(\tR\x15incompatibilityReason\x12F\n" +
	"\x10supported_levels\x18\x05 \x03(\x0e2\x1b.cachet.v1.ConsistencyLevelR\x0fsupportedLevels*\xb1\x01\n" +
	"\x10ConsistencyLevel\x12!\n" +
	"\x1dCONSISTENCY_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSISTENCY_LEVEL_STRONG\x10\x01\x12\x1d\n" +
	"\x19CONSISTENCY_LEVEL_SESSION\x10\x02\x12\x1d\n" +
	"\x19CONSISTENCY_LEVEL_BOUNDED\x10\x03\x12\x1e\n" +
	"\x1aCONSISTENCY_LEVEL_EVENTUAL\x10\x042\xc6\x02\n" +
	"\fCacheService\x12F\n" +
	"\tHandshake\x12\x1b.cachet.v1.HandshakeRequest\x1a\x1c.cachet.v1.HandshakeResponse\x124\n" +
	"\x03Get\x12\x15.cachet.v1.GetRequest\x1a\x16.cachet.v1.GetResponse\x12C\n" +
	"\bBatchGet\x12\x1a.cachet.v1.BatchGetRequest\x1a\x1b.cachet.v1.BatchGetResponse\x124\n" +
	"\x03Put\x12\x15.cachet.v1.PutRequest\x1a\x16.cachet.v1.PutResponse\x12=\n" +
	"\x06Delete\x12\x18.cachet.v1.DeleteRequest\x1a\x19.cachet.v1.DeleteResponseB;Z9github.com/Abhishek-Mallick/cachet/api/cachet/v1;cachetv1b\x06proto3"

var (
	file_cachet_v1_cachet_proto_rawDescOnce sync.Once
	file_cachet_v1_cachet_proto_rawDescData []byte
)

func file_cachet_v1_cachet_proto_rawDescGZIP() []byte {
	file_cachet_v1_cachet_proto_rawDescOnce.Do(func() {
		file_cachet_v1_cachet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cachet_v1_cachet_proto_rawDesc), len(file_cachet_v1_cachet_proto_rawDesc)))
	})
	return file_cachet_v1_cachet_proto_rawDescData
}

var file_cachet_v1_cachet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cachet_v1_cachet_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cachet_v1_cachet_proto_goTypes = []any{
	(ConsistencyLevel)(0),       // 0: cachet.v1.ConsistencyLevel
	(*SessionToken)(nil),        // 1: cachet.v1.SessionToken
	(*Record)(nil),              // 2: cachet.v1.Record
	(*ReadMeta)(nil),            // 3: cachet.v1.ReadMeta
	(*WriteMeta)(nil),           // 4: cachet.v1.WriteMeta
	(*GetRequest)(nil),          // 5: cachet.v1.GetRequest
	(*GetResponse)(nil),         // 6: cachet.v1.GetResponse
	(*BatchGetRequest)(nil),     // 7: cachet.v1.BatchGetRequest
	(*BatchGetResponse)(nil),    // 8: cachet.v1.BatchGetResponse
	(*PutRequest)(nil),          // 9: cachet.v1.PutRequest
	(*PutResponse)(nil),         // 10: cachet.v1.PutResponse
	(*DeleteRequest)(nil),       // 11: cachet.v1.DeleteRequest
	(*DeleteResponse)(nil),      // 12: cachet.v1.DeleteResponse
	(*HandshakeRequest)(nil),    // 13: cachet.v1.HandshakeRequest
	(*HandshakeResponse)(nil),   // 14: cachet.v1.HandshakeResponse
	nil,                         // 15: cachet.v1.SessionToken.WatermarksEntry
	nil,                         // 16: cachet.v1.BatchGetResponse.RecordsEntry
	(*durationpb.Duration)(nil), // 17: google.protobuf.Duration
}
var file_cachet_v1_cachet_proto_depIdxs = []int32{
	15, // 0: cachet.v1.SessionToken.watermarks:type_name -> cachet.v1.SessionToken.WatermarksEntry
	0,  // 1: cachet.v1.ReadMeta.level_served:type_name -> cachet.v1.ConsistencyLevel
	17, // 2: cachet.v1.WriteMeta.effective_staleness_bound:type_name -> google.protobuf.Duration
	0,  // 3: cachet.v1.GetRequest.level:type_name -> cachet.v1.ConsistencyLevel
	17, // 4: cachet.v1.GetRequest.staleness_bound:type_name -> google.protobuf.Duration
	1,  // 5: cachet.v1.GetRequest.session:type_name -> cachet.v1.SessionToken
	2,  // 6: cachet.v1.GetResponse.record:type_name -> cachet.v1.Record
	3,  // 7: cachet.v1.GetResponse.meta:type_name -> cachet.v1.ReadMeta
	1,  // 8: cachet.v1.GetResponse.session:type_name -> cachet.v1.SessionToken
	0,  // 9: cachet.v1.BatchGetRequest.level:type_name -> cachet.v1.ConsistencyLevel
	17, // 10: cachet.v1.BatchGetRequest.staleness_bound:type_name -> google.protobuf.Duration
	1,  // 11: cachet.v1.BatchGetRequest.session:type_name -> cachet.v1.SessionToken
	16, // 12: cachet.v1.BatchGetResponse.records:type_name -> cachet.v1.BatchGetResponse.RecordsEntry
	3,  // 13: cachet.v1.BatchGetResponse.meta:type_name -> cachet.v1.ReadMeta
	1,  // 14: cachet.v1.BatchGetResponse.session:type_name -> cachet.v1.SessionToken
	2,  // 15: cachet.v1.PutRequest.record:type_name -> cachet.v1.Record
	1,  // 16: cachet.v1.PutRequest.session:type_name -> cachet.v1.SessionToken
	4,  // 17: cachet.v1.PutResponse.meta:type_name -> cachet.v1.WriteMeta
	1,  // 18: cachet.v1.PutResponse.session:type_name -> cachet.v1.SessionToken
	1,  // 19: cachet.v1.DeleteRequest.session:type_name -> cachet.v1.SessionToken
	4,  // 20: cachet.v1.DeleteResponse.meta:type_name -> cachet.v1.WriteMeta
	1,  // 21: cachet.v1.DeleteResponse.session:type_name -> cachet.v1.SessionToken
	0,  // 22: cachet.v1.HandshakeResponse.supported_levels:type_name -> cachet.v1.ConsistencyLevel
	2,  // 23: cachet.v1.BatchGetResponse.RecordsEntry.value:type_name -> cachet.v1.Record
	13, // 24: cachet.v1.CacheService.Handshake:input_type -> cachet.v1.HandshakeRequest
	5,  // 25: cachet.v1.CacheService.Get:input_type -> cachet.v1.GetRequest
	7,  // 26: cachet.v1.CacheService.BatchGet:input_type -> cachet.v1.BatchGetRequest
	9,  // 27: cachet.v1.CacheService.Put:input_type -> cachet.v1.PutRequest
	11, // 28: cachet.v1.CacheService.Delete:input_type -> cachet.v1.DeleteRequest
	14, // 29: cachet.v1.CacheService.Handshake:output_type -> cachet.v1.HandshakeResponse
	6,  // 30: cachet.v1.CacheService.Get:output_type -> cachet.v1.GetResponse
	8,  // 31: cachet.v1.CacheService.BatchGet:output_type -> cachet.v1.BatchGetResponse
	10, // 32: cachet.v1.CacheService.Put:output_type -> cachet.v1.PutResponse
	12, // 33: cachet.v1.CacheService.Delete:output_type -> cachet.v1.DeleteResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_cachet_v1_cachet_proto_init() }
func file_cachet_v1_cachet_proto_init() {
	if File_cachet_v1_cachet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cachet_v1_cachet_proto_rawDesc), len(file_cachet_v1_cachet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cachet_v1_cachet_proto_goTypes,
		DependencyIndexes: file_cachet_v1_cachet_proto_depIdxs,
		EnumInfos:         file_cachet_v1_cachet_proto_enumTypes,
		MessageInfos:      file_cachet_v1_cachet_proto_msgTypes,
	}.Build()
	File_cachet_v1_cachet_proto = out.File
	file_cachet_v1_cachet_proto_goTypes = nil
	file_cachet_v1_cachet_proto_depIdxs = nil
}
