// Package faults renders the fault-injection record.
//
// The document is generated from what the chaos suite actually observed, never written by hand.
// That is the same rule the benchmark tables follow, and for the same reason: a fault record is a
// claim about behaviour under failure, and a claim nobody can regenerate is a claim nobody should
// believe.
package faults

import (
	"fmt"
	"sort"
	"strings"
)

// Record is one injected fault and what it proved. Written by the test that injects it.
type Record struct {
	Number      int    `json:"number"`
	Title       string `json:"title"`
	Injection   string `json:"injection"`
	Claim       string `json:"claim"`
	Fired       string `json:"fired"`
	Observed    string `json:"observed"`
	Explanation string `json:"explanation"`
}

// Catalogue is the planned set, so the document can state what is NOT covered.
//
// Without it, a file describing four passing faults reads as completeness. The denominator is the
// honest part.
var Catalogue = map[int]string{
	1: "Cache node killed mid-traffic",
	2: "Cache node slow, not dead",
	3: "Cache partitioned from the engine",
	4: "Valkey evicts under memory pressure",
	5: "Shard killed mid-transaction",
	6: "Binlog tailer killed mid-stream",
	7: "Tailer rewound to an old checkpoint",
	8: "Clock skew injected between nodes",
	9: "Lease holder dies during a slow fill",
}

// Render produces FAULTS.md.
func Render(records []Record) string {
	sorted := append([]Record(nil), records...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Number < sorted[j].Number })

	covered := make(map[int]bool, len(sorted))
	for _, r := range sorted {
		covered[r.Number] = true
	}

	var b strings.Builder
	b.WriteString("# Faults, and what explained them\n\n")
	b.WriteString("> **Generated by the chaos suite. Do not edit.** Regenerate with `make test-chaos`,\n")
	b.WriteString("> then `go run ./cmd/benchctl faults`.\n>\n")
	b.WriteString("> **The bar is not that Cachet survived.** Surviving a fault is table stakes; every cache\n")
	b.WriteString("> survives its backing store being slow. Each entry below has to name the command or metric\n")
	b.WriteString("> that tells an operator *why* — an entry that can only say \"the system recovered\" has not\n")
	b.WriteString("> met the bar and is not recorded.\n>\n")
	b.WriteString("> Every entry also carries the evidence that its injection actually fired. A toxic that\n")
	b.WriteString("> silently failed to apply produces a serene green test asserting nothing.\n\n")

	fmt.Fprintf(&b, "**Coverage: %d of %d.**\n\n", len(sorted), len(Catalogue))

	if len(sorted) > 0 {
		b.WriteString("| # | Fault | Explained by |\n|---|---|---|\n")
		for _, r := range sorted {
			fmt.Fprintf(&b, "| %d | ✅ %s | %s |\n", r.Number, r.Title, firstLine(r.Explanation))
		}
		b.WriteString("\n")
	}

	for _, r := range sorted {
		fmt.Fprintf(&b, "## %d. %s\n\n", r.Number, r.Title)
		fmt.Fprintf(&b, "**Injection.** %s\n\n", r.Injection)
		fmt.Fprintf(&b, "**Claim.** %s\n\n", r.Claim)
		fmt.Fprintf(&b, "**The injection fired.** %s\n\n", r.Fired)
		fmt.Fprintf(&b, "**Observed.** %s\n\n", r.Observed)
		fmt.Fprintf(&b, "**Explained by.** %s\n\n", r.Explanation)
	}

	var outstanding []int
	for n := range Catalogue {
		if !covered[n] {
			outstanding = append(outstanding, n)
		}
	}
	sort.Ints(outstanding)

	b.WriteString("## Not yet covered\n\n")
	if len(outstanding) == 0 {
		b.WriteString("Nothing. Every fault in the catalogue has an entry above.\n")
		return b.String()
	}
	b.WriteString("These are planned and not yet recorded. They are listed so this document cannot be\n")
	b.WriteString("mistaken for a complete one.\n\n")
	for _, n := range outstanding {
		fmt.Fprintf(&b, "- **%d.** %s\n", n, Catalogue[n])
	}
	return b.String()
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
