#!/usr/bin/env python3
"""Generate the Homebrew formula from a release's published checksums.

The formula lives in THIS repository rather than a separate `homebrew-<name>` tap. Homebrew taps
any repository when given its URL, so a second repository would buy nothing and cost a personal
access token — `GITHUB_TOKEN` cannot write to another repo, but it can write to this one.

Every value here comes from the checksums file the release actually published. Typing a sha256 by
hand is how a formula ends up pointing at bytes nobody verified.

    python3 scripts/gen-homebrew-formula.py --version 0.1.0 --checksums dist/checksums.txt
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Formula" / "cachetctl.rb"

# The platforms a formula can serve. Anything else in the checksums file is ignored.
PLATFORMS = {
    "darwin_arm64": ("on_macos", "on_arm"),
    "darwin_amd64": ("on_macos", "on_intel"),
    "linux_arm64": ("on_linux", "on_arm"),
    "linux_amd64": ("on_linux", "on_intel"),
}

TEMPLATE = '''# Cachet's operator CLI.
#
# Generated by scripts/gen-homebrew-formula.py from the checksums of a published release. Do not
# edit by hand.
#
# This formula lives in the main repository rather than a separate `homebrew-cachet` tap, because
# Homebrew taps any repository when given its URL:
#
#     brew tap abhishek-mallick/cachet https://github.com/Abhishek-Mallick/cachet
#     brew trust abhishek-mallick/cachet
#     brew install cachetctl
class Cachetctl < Formula
  desc "Operator CLI for Cachet - health, routing, key inspection, benchmarks"
  homepage "https://github.com/Abhishek-Mallick/cachet"
  version "{version}"
  license "Apache-2.0"

{blocks}
  def install
    # Only the operator CLI. The engine belongs in a container next to a service, not in a
    # developer's /usr/local/bin.
    bin.install "cachetctl"
  end

  test do
    assert_match "cachetctl", shell_output("#{{bin}}/cachetctl version")
  end
end
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True, help="release version, without a leading v")
    ap.add_argument("--checksums", required=True, type=Path)
    args = ap.parse_args()

    version = args.version.lstrip("v")
    sums = {}
    for line in args.checksums.read_text().splitlines():
        parts = line.split()
        if len(parts) == 2:
            sums[parts[1]] = parts[0]

    found = {}
    for platform in PLATFORMS:
        archive = f"cachet_{version}_{platform}.tar.gz"
        if archive in sums:
            found[platform] = (archive, sums[archive])

    # A formula missing a platform silently stops serving it, and the first report is a user on
    # that platform. Refusing is louder and cheaper.
    missing = sorted(set(PLATFORMS) - set(found))
    if missing:
        print(f"refusing to write: no archive for {', '.join(missing)} in {args.checksums}",
              file=sys.stderr)
        return 1

    by_os: dict[str, list[str]] = {}
    for platform, (archive, digest) in found.items():
        os_block, arch_block = PLATFORMS[platform]
        url = f"https://github.com/Abhishek-Mallick/cachet/releases/download/v{version}/{archive}"
        by_os.setdefault(os_block, []).append(
            f"    {arch_block} do\n"
            f'      url "{url}"\n'
            f'      sha256 "{digest}"\n'
            f"    end"
        )

    blocks = ""
    for os_block in ("on_macos", "on_linux"):
        inner = "\n".join(by_os[os_block])
        blocks += f"  {os_block} do\n{inner}\n  end\n\n"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.format(version=version, blocks=blocks))
    print(f"wrote {OUT.relative_to(ROOT)} for v{version}, {len(found)} platforms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
