package harness

import (
	"bufio"
	"fmt"
	"io"
	"math"
	"sort"
	"strconv"
	"strings"
)

// Microbenchmark tracking, per commit.
//
// A deliberate scope limit runs through this file. These numbers are produced on a shared CI runner
// — the exact environment docs/cachet-benchmarking.md §3.7 says gives latency that is "neither
// predictable nor representative". They are therefore a REGRESSION SIGNAL and never a published
// figure, and the rendered file says so in its own header rather than leaving it to be rediscovered.
//
// What survives that caveat is worth having:
//
//   - allocs/op and B/op are essentially deterministic. They do not depend on how fast or how busy
//     the machine is, so a change in them is a real change in the code, every time.
//   - ns/op is noisy in absolute terms but still catches the failures that matter. The admission
//     defect that cost 629ms of tail latency showed up as a 4x microbenchmark regression, which no
//     amount of runner noise would have hidden.

// BenchResult is one parsed benchmark line.
type BenchResult struct {
	Name        string
	NsPerOp     float64
	BytesPerOp  int64
	AllocsPerOp int64
}

// BenchRow is one commit's results.
type BenchRow struct {
	Commit  string
	Date    string
	Results []BenchResult
}

// ParseBenchmarks reads `go test -bench` output.
//
// It ignores everything that is not a benchmark line rather than failing on it, because the same
// stream carries package headers, PASS lines and build output — and a parser that rejected those
// would turn a successful run into a failed workflow.
func ParseBenchmarks(r io.Reader) ([]BenchResult, error) {
	var out []BenchResult

	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 4 || !strings.HasPrefix(fields[0], "Benchmark") {
			continue
		}
		// fields: Name-N  iterations  <ns> ns/op  [<b> B/op]  [<a> allocs/op]
		if fields[3] != "ns/op" {
			continue
		}
		ns, err := strconv.ParseFloat(fields[2], 64)
		if err != nil {
			continue
		}

		res := BenchResult{Name: trimProcSuffix(fields[0]), NsPerOp: ns}
		for i := 4; i+1 < len(fields); i += 2 {
			v, err := strconv.ParseInt(fields[i], 10, 64)
			if err != nil {
				continue
			}
			switch fields[i+1] {
			case "B/op":
				res.BytesPerOp = v
			case "allocs/op":
				res.AllocsPerOp = v
			}
		}
		out = append(out, res)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("harness: read benchmark output: %w", err)
	}
	return out, nil
}

// trimProcSuffix removes the -N that go test appends.
//
// N is the runner's GOMAXPROCS. Keeping it would make the same benchmark a different column on a
// 4-core runner than on an 8-core one, so the table would sprout a duplicate column every time
// GitHub changed its fleet — and the history either side of the change would stop being comparable.
func trimProcSuffix(name string) string {
	if i := strings.LastIndexByte(name, '-'); i > 0 {
		if _, err := strconv.Atoi(name[i+1:]); err == nil {
			return name[:i]
		}
	}
	return name
}

const benchTableHeader = `# Benchmark history, per commit

> **Generated by CI. Do not edit.** Updated by ` + "`.github/workflows/bench.yml`" + ` on every push
> that touches ` + "`internal/**` or `pkg/**`" + `. Every row here was measured by the same class of
> runner, which is the only reason the rows are comparable to each other at all. Do not add one by
> hand: a row measured on a developer machine is indistinguishable from a CI row and reads as a
> regression when the only thing that changed was the hardware.
>
> **These are regression signals, not published benchmarks.** They run on a shared GitHub Actions
> runner, which is the environment [the benchmarking methodology](../docs/cachet-benchmarking.md)
> describes as giving latency that is neither predictable nor representative. Do not quote a ns/op
> from this file as a measurement of Cachet.
>
> **The allocs/op column is the one to trust.** Allocation counts do not depend on how fast or how
> busy the machine is, so a change there is a real change in the code every time. ns/op is noisy in
> absolute terms but still catches what matters: the admission defect that cost 630ms of tail
> latency showed up here as a 4x regression, which no amount of runner noise would have hidden.
>
> Published figures live in the [README benchmark table](../README.md#benchmarks), measured by
> ` + "`make bench`" + ` on a host whose characteristics are disclosed.

`

// RenderBenchTable folds a new row into an existing table, newest first.
//
// The whole file is re-rendered from the parsed rows rather than appended to, so a benchmark that
// appears or disappears reshapes the columns correctly instead of leaving the table misaligned.
func RenderBenchTable(existing []byte, row BenchRow, keep int) string {
	if keep <= 0 {
		keep = 25
	}

	rows := append([]BenchRow{row}, parseBenchTable(existing)...)

	// De-duplicate by commit, keeping the newest entry. A workflow re-run must update the row
	// rather than add a second one for the same commit.
	seen := make(map[string]bool, len(rows))
	unique := make([]BenchRow, 0, len(rows))
	for _, r := range rows {
		if seen[r.Commit] {
			continue
		}
		seen[r.Commit] = true
		unique = append(unique, r)
	}
	if len(unique) > keep {
		unique = unique[:keep]
	}

	names := benchNames(unique)

	var b strings.Builder
	b.WriteString(benchTableHeader)

	b.WriteString("| Commit | Date |")
	for _, n := range names {
		fmt.Fprintf(&b, " %s<br/><sub>ns/op · allocs/op</sub> |", strings.TrimPrefix(n, "Benchmark"))
	}
	b.WriteString(" Trend<br/><sub>ns/op vs previous</sub> |")
	b.WriteString("\n|---|---|")
	for range names {
		b.WriteString("---|")
	}
	b.WriteString("---|\n")

	indexed := make([]map[string]BenchResult, len(unique))
	for i, r := range unique {
		byName := make(map[string]BenchResult, len(r.Results))
		for _, res := range r.Results {
			byName[res.Name] = res
		}
		indexed[i] = byName
	}

	for i, r := range unique {
		byName := indexed[i]
		fmt.Fprintf(&b, "| `%s` | %s |", r.Commit, r.Date)
		for _, n := range names {
			res, ok := byName[n]
			if !ok {
				// A gap, never a zero: a zero would read as "this became infinitely fast" on any
				// graph drawn from this table.
				b.WriteString(" — |")
				continue
			}
			fmt.Fprintf(&b, " %s · %d |", formatNs(res.NsPerOp), res.AllocsPerOp)
		}
		// Rows are newest-first, so the commit BEFORE this one is the next row down. The last row
		// has nothing behind it and gets a gap rather than a 0% claiming no change was measured.
		if i+1 < len(indexed) {
			fmt.Fprintf(&b, " %s |", trendCell(byName, indexed[i+1]))
		} else {
			b.WriteString(" — |")
		}
		b.WriteString("\n")
	}

	renderTrendSection(&b, unique, names)
	return b.String()
}

// sparkRunes are the eight block heights a sparkline is drawn from.
var sparkRunes = []rune("▁▂▃▄▅▆▇█")

// Sparkline renders a series as one line of block characters.
//
// The table answers "what is this number now"; a sparkline answers "what has it been doing", which
// is the question a regression hunt actually starts from. It is drawn oldest-to-newest so it reads
// like every other chart, even though the table above it is newest-first.
//
// A flat series renders flat. Normalising a series with no variation would turn measurement noise
// of zero into a dramatic shape, which is the most common case and the worst one to dramatise.
func Sparkline(values []float64) string {
	if len(values) == 0 {
		return ""
	}

	lo, hi := values[0], values[0]
	for _, v := range values {
		lo = math.Min(lo, v)
		hi = math.Max(hi, v)
	}
	if hi == lo {
		return strings.Repeat(string(sparkRunes[0]), len(values))
	}

	var b strings.Builder
	for _, v := range values {
		idx := int((v - lo) / (hi - lo) * float64(len(sparkRunes)-1))
		b.WriteRune(sparkRunes[idx])
	}
	return b.String()
}

// geomeanNs is the geometric mean of a commit's ns/op across the named benchmarks.
//
// Geometric rather than arithmetic because the benchmarks differ by orders of magnitude: an
// arithmetic mean would let the slowest one drown out a doubling in every other. Only benchmarks
// present in BOTH commits are compared, so a newly added benchmark cannot masquerade as a
// regression.
func geomeanNs(results map[string]BenchResult, names []string) (float64, bool) {
	sum, n := 0.0, 0
	for _, name := range names {
		r, ok := results[name]
		if !ok || r.NsPerOp <= 0 {
			continue
		}
		sum += math.Log(r.NsPerOp)
		n++
	}
	if n == 0 {
		return 0, false
	}
	return math.Exp(sum / float64(n)), true
}

// trendCell renders one row's change against the commit before it.
//
// The bar is a reading aid, not a measurement: the percentage is the number, and the header above
// this table is explicit that ns/op on a shared runner is a regression signal rather than a
// published figure. Allocation deltas are called out separately because those ARE trustworthy — a
// change there is a real change in the code every time.
func trendCell(cur, prev map[string]BenchResult) string {
	shared := make([]string, 0, len(cur))
	for name := range cur {
		if _, ok := prev[name]; ok {
			shared = append(shared, name)
		}
	}
	sort.Strings(shared)

	curMean, ok1 := geomeanNs(cur, shared)
	prevMean, ok2 := geomeanNs(prev, shared)
	if !ok1 || !ok2 || prevMean == 0 {
		return "—"
	}

	pct := (curMean/prevMean - 1) * 100

	var allocDelta int64
	for _, name := range shared {
		allocDelta += cur[name].AllocsPerOp - prev[name].AllocsPerOp
	}

	if allocDelta == 0 && looksLikeHostEffect(cur, prev, shared) {
		// Every benchmark moved the same way by a similar amount, and nothing allocated
		// differently. Code changes do not do that; quieter runners do.
		return fmt.Sprintf("≈ %+.0f%% · host?", pct)
	}

	cell := fmt.Sprintf("%s %+.0f%%", trendBar(pct), pct)
	if allocDelta != 0 {
		cell += fmt.Sprintf(" · allocs %+d", allocDelta)
	}
	return cell
}

// looksLikeHostEffect reports whether a commit's movement is better explained by the machine than
// by the code.
//
// Observed on 2026-09-18: a commit touching only a Makefile, a README, a Dockerfile and a Helm
// chart came back 23-25% faster across five unrelated benchmarks with zero change in allocations,
// and the trend column reported a 25% improvement. Nothing on the request path had changed.
//
// The three conditions together are what make it safe to say so. Any one alone would be wrong:
// unrelated benchmarks do sometimes move together, a real optimisation can leave allocations alone,
// and small movements are noise either way.
func looksLikeHostEffect(cur, prev map[string]BenchResult, shared []string) bool {
	// Two benchmarks moving together is a coincidence; several is a pattern.
	if len(shared) < 3 {
		return false
	}

	deltas := make([]float64, 0, len(shared))
	for _, name := range shared {
		c, p := cur[name], prev[name]
		if c.NsPerOp <= 0 || p.NsPerOp <= 0 {
			return false
		}
		deltas = append(deltas, (c.NsPerOp/p.NsPerOp-1)*100)
	}

	lo, hi := deltas[0], deltas[0]
	for _, d := range deltas {
		// One benchmark moving the other way means something real happened.
		if (d > 0) != (deltas[0] > 0) {
			return false
		}
		lo, hi = math.Min(lo, d), math.Max(hi, d)
	}

	// Below the noise floor there is nothing to explain either way, and above a tight spread the
	// benchmarks are not moving uniformly — one of them changed more than the others, which is what
	// a code change looks like.
	return math.Abs(lo) >= uniformShiftFloor && hi-lo <= uniformShiftSpread
}

// uniform reports whether every movement shares a direction and a rough magnitude.
func uniform(deltas []float64) bool {
	if len(deltas) < 3 {
		return false
	}
	lo, hi := deltas[0], deltas[0]
	for _, d := range deltas {
		if (d > 0) != (deltas[0] > 0) {
			return false
		}
		lo, hi = math.Min(lo, d), math.Max(hi, d)
	}
	return math.Abs(lo) >= uniformShiftFloor && hi-lo <= uniformShiftSpread
}

// allocationsFlat reports whether no benchmark's allocation count moved across the whole history.
// Allocation counts do not depend on how busy a machine is, so one that moved means the code did.
func allocationsFlat(rows []BenchRow, names []string) bool {
	for _, name := range names {
		var seen []int64
		for _, r := range rows {
			for _, res := range r.Results {
				if res.Name == name {
					seen = append(seen, res.AllocsPerOp)
				}
			}
		}
		for _, a := range seen {
			if a != seen[0] {
				return false
			}
		}
	}
	return true
}

const (
	// uniformShiftFloor is the smallest movement worth calling anything at all.
	uniformShiftFloor = 10.0

	// uniformShiftSpread is how far apart the individual movements may be and still count as one
	// shift. Ten points is wide enough for runner variance and narrow enough that an optimisation
	// of one code path, which moves one benchmark far more than the rest, falls outside it.
	uniformShiftSpread = 10.0
)

// trendBar draws the magnitude of a change, growing in the direction of the change.
//
// Slower is drawn with full blocks and faster with light ones, so a regression is visible without
// reading the sign. A change under 2% draws nothing: run-to-run noise on a shared runner is bigger
// than that, and drawing it would invite reading noise as signal.
func trendBar(pct float64) string {
	mag := math.Abs(pct)
	switch {
	case mag < 2:
		return "▬"
	case mag < 10:
		return pick(pct, "▲", "▽")
	case mag < 50:
		return pick(pct, "▲▲", "▽▽")
	default:
		return pick(pct, "▲▲▲", "▽▽▽")
	}
}

func pick(pct float64, slower, faster string) string {
	if pct > 0 {
		return slower
	}
	return faster
}

// renderTrendSection draws one sparkline per benchmark, oldest to newest.
func renderTrendSection(b *strings.Builder, rows []BenchRow, names []string) {
	if len(rows) < 2 {
		return
	}

	b.WriteString("\n## Trend\n\n")
	b.WriteString("One line per benchmark, oldest to newest, scaled to that benchmark's own range —\n")
	b.WriteString("so the shapes show movement and cannot be compared BETWEEN benchmarks. Read them for\n")
	b.WriteString("direction; read the table for values.\n\n")
	b.WriteString("```\n")

	width := 0
	for _, n := range names {
		width = max(width, len(strings.TrimPrefix(n, "Benchmark")))
	}
	endToEnd := make([]float64, 0, len(names))

	for _, name := range names {
		var series []float64
		// rows are newest-first; a chart reads the other way.
		for i := len(rows) - 1; i >= 0; i-- {
			for _, res := range rows[i].Results {
				if res.Name == name {
					series = append(series, res.NsPerOp)
				}
			}
		}
		if len(series) < 2 {
			continue
		}
		oldest, newest := series[0], series[len(series)-1]
		pct := 0.0
		if oldest > 0 {
			pct = (newest/oldest - 1) * 100
		}
		// The magnitude sits beside the shape deliberately. Scaled to its own range, a sparkline of
		// two points spans top to bottom whether the change was 1% or 1000%.
		fmt.Fprintf(b, "%-*s  %s  %s → %s  (%+.0f%%)\n",
			width, strings.TrimPrefix(name, "Benchmark"), Sparkline(series),
			formatNs(oldest), formatNs(newest), pct)
		endToEnd = append(endToEnd, pct)
	}
	b.WriteString("```\n")

	if uniform(endToEnd) && allocationsFlat(rows, names) {
		b.WriteString("\nEvery benchmark above moved the same way by a similar amount, and no " +
			"allocation count\nchanged. That is usually the MACHINE rather than the code: " +
			"unrelated code paths do not\nget uniformly faster together, and a change that made " +
			"them faster would almost always\nshow up in allocations too.\n")
	}
}

// RerenderBenchTable redraws an existing history with the current renderer, adding no row.
//
// A change to this package's output format would otherwise leave the committed file stale until
// some unrelated commit happened to touch the request path. Re-rendering is explicitly not
// recording: nothing here measures anything, so the honesty rule that a row must come from CI is
// untouched.
func RerenderBenchTable(existing []byte, keep int) string {
	rows := parseBenchTable(existing)
	if len(rows) == 0 {
		return string(existing)
	}
	// Feed the newest row back through the normal path; de-duplication by commit collapses it onto
	// the row already there, so the history is redrawn rather than extended.
	return RenderBenchTable(existing, rows[0], keep)
}

// benchNames is every benchmark seen across the kept rows, in a stable order.
func benchNames(rows []BenchRow) []string {
	seen := map[string]bool{}
	for _, r := range rows {
		for _, res := range r.Results {
			seen[res.Name] = true
		}
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// parseBenchTable reads back the rows of a previously rendered table.
func parseBenchTable(existing []byte) []BenchRow {
	if len(existing) == 0 {
		return nil
	}

	lines := strings.Split(string(existing), "\n")
	var names []string
	var rows []BenchRow

	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "| Commit |"):
			names = nil
			for _, cell := range splitRow(line)[2:] {
				name, _, _ := strings.Cut(cell, "<br/>")
				name = strings.TrimSpace(name)
				// Trend is a rendering of the other columns, not a measurement.
				//
				// Belt and braces, and labelled as such: nothing downstream currently records a
				// result for it either, because parseNs rejects a cell like "▲▲ +12%". This skip is
				// what keeps that true if the trend cell ever starts carrying a duration — at which
				// point the column would otherwise be read back as a benchmark and re-rendered as
				// one. TestTheTrendColumnSurvivesARoundTrip pins the column count that would break.
				if name == "Trend" {
					continue
				}
				names = append(names, "Benchmark"+name)
			}
		case strings.HasPrefix(line, "| `"):
			cells := splitRow(line)
			if len(cells) < 2 {
				continue
			}
			row := BenchRow{Commit: strings.Trim(cells[0], "` "), Date: strings.TrimSpace(cells[1])}
			for i, cell := range cells[2:] {
				if i >= len(names) || strings.TrimSpace(cell) == "—" {
					continue
				}
				nsText, allocsText, ok := strings.Cut(cell, "·")
				if !ok {
					continue
				}
				ns, err := parseNs(strings.TrimSpace(nsText))
				if err != nil {
					continue
				}
				allocs, _ := strconv.ParseInt(strings.TrimSpace(allocsText), 10, 64)
				row.Results = append(row.Results, BenchResult{Name: names[i], NsPerOp: ns, AllocsPerOp: allocs})
			}
			rows = append(rows, row)
		}
	}
	return rows
}

func splitRow(line string) []string {
	parts := strings.Split(strings.Trim(line, "|"), "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

// formatNs renders a duration in a unit a reader can compare at a glance.
func formatNs(ns float64) string {
	switch {
	case ns >= 1_000_000:
		return fmt.Sprintf("%.2fms", ns/1_000_000)
	case ns >= 1_000:
		return fmt.Sprintf("%.2fµs", ns/1_000)
	default:
		return fmt.Sprintf("%.1fns", ns)
	}
}

func parseNs(s string) (float64, error) {
	switch {
	case strings.HasSuffix(s, "ms"):
		v, err := strconv.ParseFloat(strings.TrimSuffix(s, "ms"), 64)
		return v * 1_000_000, err
	case strings.HasSuffix(s, "µs"):
		v, err := strconv.ParseFloat(strings.TrimSuffix(s, "µs"), 64)
		return v * 1_000, err
	case strings.HasSuffix(s, "ns"):
		return strconv.ParseFloat(strings.TrimSuffix(s, "ns"), 64)
	default:
		return 0, fmt.Errorf("harness: unrecognised duration %q", s)
	}
}
