package harness

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
)

// Microbenchmark tracking, per commit.
//
// A deliberate scope limit runs through this file. These numbers are produced on a shared CI runner
// — the exact environment docs/cachet-benchmarking.md §3.7 says gives latency that is "neither
// predictable nor representative". They are therefore a REGRESSION SIGNAL and never a published
// figure, and the rendered file says so in its own header rather than leaving it to be rediscovered.
//
// What survives that caveat is worth having:
//
//   - allocs/op and B/op are essentially deterministic. They do not depend on how fast or how busy
//     the machine is, so a change in them is a real change in the code, every time.
//   - ns/op is noisy in absolute terms but still catches the failures that matter. The admission
//     defect that cost 629ms of tail latency showed up as a 4x microbenchmark regression, which no
//     amount of runner noise would have hidden.

// BenchResult is one parsed benchmark line.
type BenchResult struct {
	Name        string
	NsPerOp     float64
	BytesPerOp  int64
	AllocsPerOp int64
}

// BenchRow is one commit's results.
type BenchRow struct {
	Commit  string
	Date    string
	Results []BenchResult
}

// ParseBenchmarks reads `go test -bench` output.
//
// It ignores everything that is not a benchmark line rather than failing on it, because the same
// stream carries package headers, PASS lines and build output — and a parser that rejected those
// would turn a successful run into a failed workflow.
func ParseBenchmarks(r io.Reader) ([]BenchResult, error) {
	var out []BenchResult

	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 4 || !strings.HasPrefix(fields[0], "Benchmark") {
			continue
		}
		// fields: Name-N  iterations  <ns> ns/op  [<b> B/op]  [<a> allocs/op]
		if fields[3] != "ns/op" {
			continue
		}
		ns, err := strconv.ParseFloat(fields[2], 64)
		if err != nil {
			continue
		}

		res := BenchResult{Name: trimProcSuffix(fields[0]), NsPerOp: ns}
		for i := 4; i+1 < len(fields); i += 2 {
			v, err := strconv.ParseInt(fields[i], 10, 64)
			if err != nil {
				continue
			}
			switch fields[i+1] {
			case "B/op":
				res.BytesPerOp = v
			case "allocs/op":
				res.AllocsPerOp = v
			}
		}
		out = append(out, res)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("harness: read benchmark output: %w", err)
	}
	return out, nil
}

// trimProcSuffix removes the -N that go test appends.
//
// N is the runner's GOMAXPROCS. Keeping it would make the same benchmark a different column on a
// 4-core runner than on an 8-core one, so the table would sprout a duplicate column every time
// GitHub changed its fleet — and the history either side of the change would stop being comparable.
func trimProcSuffix(name string) string {
	if i := strings.LastIndexByte(name, '-'); i > 0 {
		if _, err := strconv.Atoi(name[i+1:]); err == nil {
			return name[:i]
		}
	}
	return name
}

const benchTableHeader = `# Benchmark history, per commit

> **Generated by CI. Do not edit.** Updated by ` + "`.github/workflows/bench.yml`" + ` on every push
> that touches ` + "`internal/**` or `pkg/**`" + `. Every row here was measured by the same class of
> runner, which is the only reason the rows are comparable to each other at all. Do not add one by
> hand: a row measured on a developer machine is indistinguishable from a CI row and reads as a
> regression when the only thing that changed was the hardware.
>
> **These are regression signals, not published benchmarks.** They run on a shared GitHub Actions
> runner, which is the environment [the benchmarking methodology](../docs/cachet-benchmarking.md)
> describes as giving latency that is neither predictable nor representative. Do not quote a ns/op
> from this file as a measurement of Cachet.
>
> **The allocs/op column is the one to trust.** Allocation counts do not depend on how fast or how
> busy the machine is, so a change there is a real change in the code every time. ns/op is noisy in
> absolute terms but still catches what matters: the admission defect that cost 630ms of tail
> latency showed up here as a 4x regression, which no amount of runner noise would have hidden.
>
> Published figures live in the [README benchmark table](../README.md#benchmarks), measured by
> ` + "`make bench`" + ` on a host whose characteristics are disclosed.

`

// RenderBenchTable folds a new row into an existing table, newest first.
//
// The whole file is re-rendered from the parsed rows rather than appended to, so a benchmark that
// appears or disappears reshapes the columns correctly instead of leaving the table misaligned.
func RenderBenchTable(existing []byte, row BenchRow, keep int) string {
	if keep <= 0 {
		keep = 25
	}

	rows := append([]BenchRow{row}, parseBenchTable(existing)...)

	// De-duplicate by commit, keeping the newest entry. A workflow re-run must update the row
	// rather than add a second one for the same commit.
	seen := make(map[string]bool, len(rows))
	unique := make([]BenchRow, 0, len(rows))
	for _, r := range rows {
		if seen[r.Commit] {
			continue
		}
		seen[r.Commit] = true
		unique = append(unique, r)
	}
	if len(unique) > keep {
		unique = unique[:keep]
	}

	names := benchNames(unique)

	var b strings.Builder
	b.WriteString(benchTableHeader)

	b.WriteString("| Commit | Date |")
	for _, n := range names {
		fmt.Fprintf(&b, " %s<br/><sub>ns/op · allocs/op</sub> |", strings.TrimPrefix(n, "Benchmark"))
	}
	b.WriteString("\n|---|---|")
	for range names {
		b.WriteString("---|")
	}
	b.WriteString("\n")

	for _, r := range unique {
		byName := make(map[string]BenchResult, len(r.Results))
		for _, res := range r.Results {
			byName[res.Name] = res
		}
		fmt.Fprintf(&b, "| `%s` | %s |", r.Commit, r.Date)
		for _, n := range names {
			res, ok := byName[n]
			if !ok {
				// A gap, never a zero: a zero would read as "this became infinitely fast" on any
				// graph drawn from this table.
				b.WriteString(" — |")
				continue
			}
			fmt.Fprintf(&b, " %s · %d |", formatNs(res.NsPerOp), res.AllocsPerOp)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// benchNames is every benchmark seen across the kept rows, in a stable order.
func benchNames(rows []BenchRow) []string {
	seen := map[string]bool{}
	for _, r := range rows {
		for _, res := range r.Results {
			seen[res.Name] = true
		}
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// parseBenchTable reads back the rows of a previously rendered table.
func parseBenchTable(existing []byte) []BenchRow {
	if len(existing) == 0 {
		return nil
	}

	lines := strings.Split(string(existing), "\n")
	var names []string
	var rows []BenchRow

	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "| Commit |"):
			names = nil
			for _, cell := range splitRow(line)[2:] {
				name, _, _ := strings.Cut(cell, "<br/>")
				names = append(names, "Benchmark"+strings.TrimSpace(name))
			}
		case strings.HasPrefix(line, "| `"):
			cells := splitRow(line)
			if len(cells) < 2 {
				continue
			}
			row := BenchRow{Commit: strings.Trim(cells[0], "` "), Date: strings.TrimSpace(cells[1])}
			for i, cell := range cells[2:] {
				if i >= len(names) || strings.TrimSpace(cell) == "—" {
					continue
				}
				nsText, allocsText, ok := strings.Cut(cell, "·")
				if !ok {
					continue
				}
				ns, err := parseNs(strings.TrimSpace(nsText))
				if err != nil {
					continue
				}
				allocs, _ := strconv.ParseInt(strings.TrimSpace(allocsText), 10, 64)
				row.Results = append(row.Results, BenchResult{Name: names[i], NsPerOp: ns, AllocsPerOp: allocs})
			}
			rows = append(rows, row)
		}
	}
	return rows
}

func splitRow(line string) []string {
	parts := strings.Split(strings.Trim(line, "|"), "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

// formatNs renders a duration in a unit a reader can compare at a glance.
func formatNs(ns float64) string {
	switch {
	case ns >= 1_000_000:
		return fmt.Sprintf("%.2fms", ns/1_000_000)
	case ns >= 1_000:
		return fmt.Sprintf("%.2fµs", ns/1_000)
	default:
		return fmt.Sprintf("%.1fns", ns)
	}
}

func parseNs(s string) (float64, error) {
	switch {
	case strings.HasSuffix(s, "ms"):
		v, err := strconv.ParseFloat(strings.TrimSuffix(s, "ms"), 64)
		return v * 1_000_000, err
	case strings.HasSuffix(s, "µs"):
		v, err := strconv.ParseFloat(strings.TrimSuffix(s, "µs"), 64)
		return v * 1_000, err
	case strings.HasSuffix(s, "ns"):
		return strconv.ParseFloat(strings.TrimSuffix(s, "ns"), 64)
	default:
		return 0, fmt.Errorf("harness: unrecognised duration %q", s)
	}
}
