package harness

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"time"
)

// readmeTableHeader identifies the benchmark table inside the README.
const readmeTableHeader = "| Configuration | Hit rate | p99 read | Origin QPS under stampede | Staleness | Redis mem |"

// placeholder is what an unmeasured cell shows. A phase with no results keeps its placeholder
// rather than being dropped, so the table always states the full plan and shows what is still
// outstanding.
const placeholder = "—"

// phaseRows maps a phase id to the row label it fills in. The order here is the order in the table.
var phaseRows = []struct {
	phase string
	label string
}{
	{"0-baseline", "No cache"},
	{"1-ttl", "TTL only"},
	{"2-cdc", "+ CDC invalidation"},
	{"3-exact", "+ exact write-path invalidation"},
	{"4a-leases", "**+ leases**"},
	{"4b-admission", "**+ adaptive admission**"},
}

// UpdateReadme rewrites the benchmark table from the given reports.
//
// Nobody types a number into the README, ever (benchmarking doc §8). Hand-typed numbers drift as
// the code changes, and drift reads as dishonesty even when it is only laziness — which is a
// particularly bad look for a project whose entire pitch is that it proves its claims.
//
// Only the table is touched; the surrounding document is preserved byte for byte.
func UpdateReadme(path string, reports []Report) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("harness: read %s: %w", path, err)
	}

	lines := strings.Split(string(data), "\n")
	headerAt := -1
	for i, l := range lines {
		if strings.TrimSpace(l) == readmeTableHeader {
			headerAt = i
			break
		}
	}
	if headerAt == -1 {
		// Silently doing nothing would mean `make bench-report` reports success while the README
		// keeps showing placeholders.
		return errors.New("harness: no benchmark table found in " + path)
	}

	// The separator line follows the header; data rows follow that, until a blank line.
	start := headerAt + 2
	if start > len(lines) {
		return errors.New("harness: benchmark table is truncated in " + path)
	}
	end := start
	for end < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[end]), "|") {
		end++
	}

	byPhase := make(map[string]Report, len(reports))
	for _, r := range Latest(reports) {
		// W2 is the primary workload; every phase row uses it (benchmarking doc §5).
		if r.Workload != "" && r.Workload != "W2" {
			continue
		}
		byPhase[r.Phase] = r
	}

	rows := make([]string, 0, len(phaseRows))
	for _, pr := range phaseRows {
		rows = append(rows, renderRow(pr.label, byPhase[pr.phase]))
	}

	// Any previously generated provenance line is dropped before the new one is written, so
	// regenerating replaces it rather than stacking a second copy under the table.
	tail := lines[end:]
	for len(tail) > 0 && strings.HasPrefix(strings.TrimSpace(tail[0]), provenanceMarker) {
		tail = tail[1:]
	}

	out := make([]string, 0, len(lines)+len(rows)+1)
	out = append(out, lines[:start]...)
	out = append(out, rows...)
	if line := provenance(reports); line != "" {
		out = append(out, line)
	}
	out = append(out, tail...)

	return os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o600)
}

// provenanceMarker prefixes the generated line that says where the numbers came from.
const provenanceMarker = "<sub>Measured on"

// provenance renders the disclosure that must accompany every published number.
//
// Docker Desktop on macOS runs a VM with a virtualised filesystem whose I/O latency is neither
// predictable nor representative, and MyRocks is I/O-sensitive. Measuring there is perfectly
// acceptable; letting a reader assume otherwise is not (benchmarking doc §3.7).
func provenance(reports []Report) string {
	latest := Latest(reports)
	if len(latest) == 0 {
		return ""
	}

	newest := latest[0]
	for _, r := range latest[1:] {
		if r.RecordedAt.After(newest.RecordedAt) {
			newest = r
		}
	}
	if newest.Env.Host == "" {
		return ""
	}

	return fmt.Sprintf(
		"%s **%s** (%s, %d cores) · %d runs · %ds measured at %d rps · θ=%g · %s. "+
			"Generated by `make bench-report`; do not edit by hand.</sub>",
		provenanceMarker, newest.Env.Host, newest.Env.Arch, newest.Env.CoresAvailable,
		newest.Client.Runs, newest.Params.MeasureSeconds, newest.Params.Rate,
		newest.Params.ZipfTheta, newest.RecordedAt.UTC().Format("2006-01-02"))
}

func renderRow(label string, r Report) string {
	if r.Phase == "" {
		return fmt.Sprintf("| %s | %s | %s | %s | %s | %s |",
			label, placeholder, placeholder, placeholder, placeholder, placeholder)
	}

	hitRate := placeholder
	if r.Cache.HitRate > 0 {
		hitRate = fmt.Sprintf("%.1f%%", r.Cache.HitRate*100)
	}

	// The spread is printed next to the number rather than hidden in the JSON. If the run-to-run
	// spread is wider than the effect being claimed, the reader should be able to see that without
	// opening a results file.
	p99 := formatMicros(r.Client.Read.P99)
	if lo, hi := r.Client.Spread.ReadP99[0], r.Client.Spread.ReadP99[1]; hi > lo {
		p99 = fmt.Sprintf("%s <sub>(%s–%s)</sub>", p99, formatMicros(lo), formatMicros(hi))
	}
	if !r.Client.Sufficient {
		// An under-sampled number is published with a mark rather than withheld or laundered.
		p99 += " ⚠️"
	}

	originQPS := placeholder
	if r.Origin.QPS > 0 {
		originQPS = fmt.Sprintf("%.0f", r.Origin.QPS)
	}

	memory := placeholder
	if r.Cache.MemoryBytes > 0 {
		memory = fmt.Sprintf("%.0f MB", float64(r.Cache.MemoryBytes)/(1<<20))
	}

	return fmt.Sprintf("| %s | %s | %s | %s | %s | %s |",
		label, hitRate, p99, originQPS, placeholder, memory)
}

// formatMicros renders a microsecond count the way a reader thinks about it.
func formatMicros(us int64) string {
	if us == 0 {
		return placeholder
	}
	d := time.Duration(us) * time.Microsecond
	switch {
	case d < time.Millisecond:
		return fmt.Sprintf("%dµs", us)
	case d < time.Second:
		return fmt.Sprintf("%.2fms", d.Seconds()*1000)
	default:
		return fmt.Sprintf("%.2fs", d.Seconds())
	}
}
